### ISSUE TITLE
Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by u873838** [sonofmagic/graphql-depth-limit-ts#2]
After swapping out graphql-depth-limit with this library, we sometimes get the following error message:

```
TypeError: Cannot read properties of undefined (reading 'kind')
at determineDepth (<root>/node_modules/graphql-depth-limit-ts/dist/index.js:67:18)
at determineDepth (<root>/node_modules/graphql-depth-limit-ts/dist/index.js:77:20)
at <root>/node_modules/graphql-depth-limit-ts/dist/index.js:75:77
at Array.map (<anonymous>)
at determineDepth (<root>/node_modules/graphql-depth-limit-ts/dist/index.js:75:58)
at <root>/node_modules/graphql-depth-limit-ts/dist/index.js:81:80
at Array.map (<anonymous>)
at determineDepth (<root>/node_modules/graphql-depth-limit-ts/dist/index.js:81:61)
at <root>/node_modules/graphql-depth-limit-ts/dist/index.js:33:33
at <root>/node_modules/graphql/validation/validate.js:87:25
```

I believe this may happen if there is a fragment in the query that does not exist.

**Comment by sonofmagic** [comment]
Hello, this should be `graphql-depth-limit` its original problem.

Can you provide a test case for this issue? In this way, I can fix this package for this situation.
